#PBS -N GR_MC
#PBS -l select=1:ncpus=40  
#PBS -l walltime=336:00:00 
#PBS -m abe
#PBS -M edmilson.roque.santos@usp.br
#PBS -o /home/edroque/Greedy_Reconstruction/MC_EBP/output
#PBS -e /home/edroque/Greedy_Reconstruction/MC_EBP/erros

mkdir -p /lustre/edroque/Greedy_Reconstruction/MC_EBP_lgth/

cp -r /home/edroque/Greedy_Reconstruction/MC_EBP/. /lustre/edroque/Greedy_Reconstruction/MC_EBP_lgth

cd /lustre/edroque/Greedy_Reconstruction/MC_EBP_lgth/

python mp_lgth.py > saida
