#PBS -N nc_MC_N
#PBS -l select=1:ncpus=40
#PBS -l walltime=336:00:00
#PBS -m abe
#PBS -M edmilson.roque.santos@usp.br
#PBS -o /home/edroque/Greedy_Reconstruction/MC_EBP/output_nc_N.out
#PBS -e /home/edroque/Greedy_Reconstruction/MC_EBP/erros_nc_N.out

mkdir -p /lustre/edroque/Greedy_Reconstruction/MC_EBP_nc_N/

cp -a /home/edroque/Greedy_Reconstruction/MC_EBP/. /lustre/edroque/Greedy_Reconstruction/MC_EBP_nc_N

cd /lustre/edroque/Greedy_Reconstruction/MC_EBP_nc_N/

python mp_nc.py > saida_nc_N.txt
