#PBS -N nc_MC
#PBS -l select=1:ncpus=40  
#PBS -l walltime=336:00:00 
#PBS -m abe
#PBS -M edmilson.roque.santos@usp.br
#PBS -o /home/edroque/Greedy_Reconstruction/MC_EBP/output
#PBS -e /home/edroque/Greedy_Reconstruction/MC_EBP/erros

source anaconda3/bin/activate

mkdir -p /lustre/edroque/Collaboration/Greedy_Reconstruction/MC_EBP/

cp -a /home/edroque/Greedy_Reconstruction/MC_EBP/.  /lustre/edroque/Greedy_Reconstruction/MC_EBP

cd /lustre/edroque/Greedy_Reconstruction/MC_EBP

python mp_nc.py > saida.txt
