#PBS -N nc_MC_lat
#PBS -l select=1:ncpus=10
#PBS -l walltime=336:00:00
#PBS -m abe
#PBS -M edmilson.roque.santos@usp.br
#PBS -o /home/edroque/Greedy_Reconstruction/MC_EBP/output_nc_lat.out
#PBS -e /home/edroque/Greedy_Reconstruction/MC_EBP/erros_nc_lat.err

mkdir -p /lustre/edroque/Greedy_Reconstruction/MC_EBP_nc_lat/

cp -a /home/edroque/Greedy_Reconstruction/MC_EBP/. /lustre/edroque/Greedy_Reconstruction/MC_EBP_nc_lat

cd /lustre/edroque/Greedy_Reconstruction/MC_EBP_nc_lat/

python mp_nc.py > saida_nc.txt
